### ISSUE TITLE
tagging strategy question

### ISSUE THREAD

**Issue by ReenigneArcher** [DoozyX/clang-format-lint-action#76]
Starting within the last 24 hours, there is an error that distutils is missing.

```txt
> Run DoozyX/clang-format-lint-action@v0.18
  with:
    source: ./tests/unit/test_rswrapper.cpp ./tests/unit/test_httpcommon.cpp ./tests/unit/test_network.cpp ./tests/unit/platform/test_common.cpp ./tests/unit/test_logging.cpp ./tests/unit/test_video.cpp ./tests/unit/test_stream.cpp ./tests/unit/test_entry_handler.cpp ./tests/unit/test_audio.cpp ./tests/unit/test_file_handler.cpp ./tests/unit/test_mouse.cpp ./tests/tests_events.h ./tests/tests_main.cpp ./tests/tests_environment.h ./tests/tests_common.h ./tests/tests_log_checker.h ./tools/audio.cpp ./tools/sunshinesvc.cpp ./tools/ddprobe.cpp ./tools/dxgi.cpp ./src/video.cpp ./src/stream.h ./src/audio.h ./src/crypto.cpp ./src/audio.cpp ./src/uuid.h ./src/stat_trackers.cpp ./src/confighttp.cpp ./src/rswrapper.h ./src/cbs.cpp ./src/move_by_copy.h ./src/file_handler.h ./src/upnp.h ./src/thread_pool.h ./src/logging.cpp ./src/task_pool.h ./src/crypto.h ./src/main.cpp ./src/utility.h ./src/nvhttp.cpp ./src/system_tray.h ./src/httpcommon.cpp ./src/globals.h ./src/httpcommon.h ./src/rswrapper.c ./src/nvhttp.h ./src/sync.h
    extensions: c,cpp,h,hpp,m,mm
    style: file
    inplace: false
    exclude: none
    clangFormatVersion: 18
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.5/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.5/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.5/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.5/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.5/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.5/x64/lib
/usr/bin/docker run --name fa00690cbf43705c4437d8a77391aca692674_7fe505 --label 8fa006 --workdir /github/workspace --rm -e "pythonLocation" -e "PKG_CONFIG_PATH" -e "Python_ROOT_DIR" -e "Python2_ROOT_DIR" -e "Python3_ROOT_DIR" -e "LD_LIBRARY_PATH" -e "INPUT_SOURCE" -e "INPUT_EXTENSIONS" -e "INPUT_STYLE" -e "INPUT_INPLACE" -e "INPUT_EXCLUDE" -e "INPUT_CLANGFORMATVERSION" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" 
Traceback (most recent call last):
  File "/run-clang-format.py", line 26, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
```

I guess this is because I'm using v0.18 and not v0.18.2 (but I need to confirm this). Is there any plan to update the v0.18 tag like many actions do? Ideally updating the version in the workflow files wouldn't be necessary unless there's a breaking change in a higher version.

**Comment by DoozyX** [comment]
Could you rerun the action again and let me know if it works as expected please

**Comment by ReenigneArcher** [comment]
Unfortunately, the same result. I see the tag commits were updated, so I'm not sure why.

I think many actions delete the tag and re-create it. e.g. a when a v2.4 is released, they delete the existing v2 and recreate it with the same parameters as the v2.4.

**Comment by brandon-exact** [comment]
I also have this issue.

**Comment by DoozyX** [comment]
Yes, that was correct, I updated v17 and v18 releases but with different tag name, changing the tag name back to the original one with pin of different version solved it. Should be resolved now

**Comment by ReenigneArcher** [comment]
Confirming this is fixed. Thank you!

**Comment by brandon-exact** [comment]
I still get the error for `DoozyX/clang-format-lint-action@v0.16.2`

**Comment by brandon-exact** [comment]
@DoozyX

**Comment by DoozyX** [comment]
@brandon-exact should be fixed also for previous releases
